ONE_SECOND = 1000

MAX_PROCESSES = 42

LAST_ALIVE_STARVATION_LEVEL = 5
DEAD_STARVATION_LEVEL = 6

MIN_CPU_COUNT = 1
MAX_CPU_COUNT = 16
MIN_PROCESSES_AT_STARTUP = 1
MAX_PROCESSES_AT_STARTUP = 42
MIN_RAM_ROWS = 1
MAX_RAM_ROWS = 11

MAX_PAGES_PER_PROCESS = 4
