
name: pytest
on: [pull_request]


jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      uses: VaultVulp/action-pipenv@v2.0.1
      with:
        command: sync --dev
    - name: Run pylint
      uses: VaultVulp/action-pipenv@v2.0.1
      with:
        command:  run pytest
